# Generated by Django 4.2.1 on 2023-07-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esp_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('light_intensity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=3)),
                ('soil_moisture', models.DecimalField(decimal_places=2, max_digits=5)),
                ('soil_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('flow_intensity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
