# Generated by Django 4.2.1 on 2023-07-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_esp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp_data',
            name='esp_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='esp_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
