# Generated by Django 4.2.1 on 2023-07-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_esp', '0002_esp_data_esp_id_alter_esp_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp_data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='esp_data',
            name='light_intensity',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='esp_data',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
