# Generated by Django 4.2.1 on 2023-08-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handle_esp', '0003_alter_esp_data_id_alter_esp_data_light_intensity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crops_description', models.TextField(default='Any')),
            ],
        ),
        migrations.CreateModel(
            name='Esp_device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handle_esp.location')),
            ],
        ),
        migrations.AlterField(
            model_name='esp_data',
            name='esp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handle_esp.esp_device'),
        ),
    ]
